export const SET_PROFILE = "SET_PROFILE";
export const SET_PLAYSTATE = "SET_PLAYSTATE";
export const SET_FULLSCREEN = "SET_FULLSCREEN";
export const SET_CURRENTINDEX = "SET_CURRENTINDEX";
export const SET_CURRENTLIST = "SET_CURRENTLIST";
